work_dir: work_dir/NTU60/xsub/joint/linear_tmp_test
weights: null
ignore_weights: [mask_param, encoder_q.fc, encoder_k, queue]
#start_epoch: 95
# feeder
train_feeder: feeder.ntu_STSep_feeder.Feeder_single
train_feeder_args:
  data_path: ../data/NTU60_frame50/xsub/train_position.npy
  label_path: ../data/NTU-RGB-D/xsub/train_label.pkl
  shear_amplitude: -1
  temperal_padding_ratio: -1
  mmap: True
test_feeder: feeder.ntu_STSep_feeder.Feeder_single
test_feeder_args:
  data_path: ../data/NTU60_frame50/xsub/val_position.npy
  label_path: ../data/NTU-RGB-D/xsub/val_label.pkl
  shear_amplitude: -1
  temperal_padding_ratio: -1
  mmap: True

# model
model: net.hiclr_ST.HiCLR
model_args:
  base_encoder: net.st_gated_gcn.Model
  pretrain: False
  in_channels: 3
  hidden_channels: 16
  hidden_dim: 256
  num_class: 60
  dropout: 0.0
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'
  edge_importance_weighting: True
# optim
nesterov: False
weight_decay: 0.0
base_lr: 3.
optimizer: SGD
step: [80]

# training
device: [2]
batch_size: 128
test_batch_size: 128
num_epoch: 100
stream: 'joint'

# log
save_interval: -1
eval_interval: 5


